// src/pages/Game/index.jsx
import { randomWord, checkWord } from '@scripts/words'
import { WordProposition } from '@components/Proposition'
import { useState } from 'preact/hooks'
export function Game() {
    // eslint-disable-next-line no-unused-vars
    const [wordChoosen, setWordChoosen] = useState(randomWord())
    const [propositionList, setPropositionList] = useState([])
    const addToPropositionList = (proposition) => {
        setPropositionList((prevPropositionList) => [
            ...prevPropositionList,
            proposition,
        ])
    }
    // eslint-disable-next-line no-unused-vars
    const [firstRow, setFirstRow] = useState({
        word: wordChoosen.split('').map((char, i) => {
            return i == 0 ? { char, status: 2 } : { char: '*', status: -1 }
        }),
    })
    let value = ''
    const setValue = (v) => {
        value = v
    }
    const resetValue = (e) => {
        e.target.value = ''
        setValue('')
    }
    const onInputInInput = (e) => {
        setValue(e.target.value)
        if (value.length == wordChoosen.length) {
            addToPropositionList(checkWord(wordChoosen, value))
            if (propositionList.at(-1).valid) {
                localStorage.setItem(
                    'wincount',
                    (
                        parseInt(localStorage.getItem('wincount'), 10) + 1
                    ).toString()
                )
                alert(
                    `Vous avez gagné, le mot était ${wordChoosen.toUpperCase()} trouvé en ${
                        propositionList.length
                    } essai(s).`
                )
                window.location.href = '/'
            }
            resetValue(e)
        }
    }

    return (
        <div class="flex justify-center flex-col items-center">
            <div class="w-fit border-b-2 border-white m-2">
                <WordProposition word={firstRow} />
                {propositionList.map((proposition) => (
                    // eslint-disable-next-line react/jsx-key
                    <WordProposition word={proposition} />
                ))}
            </div>
            <div class="w-full flex flex-col m-2 justify-center items-center max-w-lg mx-0">
                <input
                    class="m-1 p-1 bg-white text-black max-w-lg w-full rounded-lg"
                    type="text"
                    onInput={onInputInInput}
                />
                <div className="max-w-lg w-full flex flex-col justify-center items-center">
                    <button class="m-1 p-1 border-white border-2 bg-slate-500 text-white w-full rounded-lg">
                        Indice ?
                    </button>
                    <button class="m-1 p-1 border-white border-2 bg-slate-500 text-white w-full rounded-lg">
                        Abandon
                    </button>
                </div>
            </div>
        </div>
    )
}

// src/lib/pages/Game.svelte
<script lang="ts">
    import {
        firstWord,
        randomWord,
        newCheckWord,
        normalizeWord,
    } from "../words";
    import type { WordProposition } from "../words";
    import Proposition from "../components/Proposition.svelte";
    import type { Writable } from "svelte/store";
    import { get } from "svelte/store";
    import { updateStat } from "../libs";

    export let status: Writable<string>;
    let statusData = "";
    status.subscribe((val: string) => {
        statusData = val;
    });
    $: classes = `${statusData == "game" ? "" : "hidden"}`;

    const wordToTrove = randomWord();
    let propositionList: WordProposition[] = [];
    $: firstRow = firstWord(propositionList, wordToTrove);
    let input = "";
    const addWord = () => {
        let propositionGiven = input;
        input = "";
        propositionList.push(
            newCheckWord(
                wordToTrove,
                normalizeWord(propositionGiven.toLowerCase()),
            ),
        );

        console.log(propositionList);
        if (propositionList.at(-1).valid) {
            alert(
                `Vous avez gagné, le mot était ${wordToTrove.toUpperCase()} trouvé en ${
                    propositionList.length
                }`,
            );
            updateStat("win", 1);
        } else if (propositionList.length == 6) {
        }
    };
    $: input.length == wordToTrove.length && addWord();
    $: nbPropositions = propositionList.length;
    console.log(wordToTrove);
</script>

<div class={classes}>
    <div class="flex justify-center flex-col items-center">
        <div class="w-fit border-b-2 border-white m-2">
            <Proposition word={firstRow} />
            {#key input}
                {#each propositionList as proposition}
                    <Proposition word={proposition} />
                {/each}
            {/key}
        </div>
        <div
            class="w-full flex flex-col m-2 justify-center items-center max-w-lg mx-0"
        >
            <input
                class="m-1 p-1 bg-white text-black max-w-lg w-full rounded-lg"
                type="text"
                bind:value={input}
            />
            <div
                class="max-w-lg w-full flex flex-col justify-center items-center"
            >
                <button
                    class="m-1 p-1 border-white border-2 bg-slate-500 text-white w-full rounded-lg"
                >
                    Indice ?
                </button>
                <button
                    class="m-1 p-1 border-white border-2 bg-slate-500 text-white w-full rounded-lg"
                >
                    Abandon
                </button>
            </div>
        </div>
    </div>
</div>
